Simple freeze traffic command
wessupermare/TrainingServer pull request #9
Opened 2022-08-30 21:59 UTC by AlFaMoDz

Simple plugin for freezing a single aircraft

WIP: FREEZE ALL command

2022-08-31 11:04 UTC, wessupermare requested changes
Looks like a good idea! Pausing traffic in mid-air is a nice feature to have. Just a few bits of logic that can be cleaned up and it should be ready to go. Also consider (if you want to, it's also fine as is) making this command user-definable in case someone wants `PAUSE`, for instance. Regexes might be a way to go as they're nice and quick in C#.

2022-08-31 11:04 UTC, wessupermare commented on Plugins/FreezeScene/Plugin.cs
> +		{
I don't think this check is necessary; the function isn't called unless `CheckIntercept` returns `true`, so this will never be false. Might as well remove it and save a few cycles.

2022-08-31 11:04 UTC, wessupermare commented on Plugins/FreezeScene/Plugin.cs
> +			}
```suggestion
		aircraft.Paused = !aircraft.Paused;
		return (aircraft.Paused ? "Aircraft freezed" : "Aircraft unfreezed");
```
This `try`/`catch` is also probably unnecessary. It's highly unlikely that this property access/set is going to throw; if it does, that's a problem on my end and needs to be reported as a bug.

2022-08-31 11:04 UTC, wessupermare commented on Plugins/FreezeScene/Plugin.cs
> +		return "";
```suggestion
```
This can be removed with the removal of the `if` check above.

2022-08-31 11:04 UTC, wessupermare commented on Plugins/FreezeScene/README.md
> +The command must be sent by PM to the traffic:
I think this will work on frequency as well, no? You just have to have the aircraft selected and it _should_ go through… Let me know if it doesn't.

2022-08-31 21:29 UTC, AlFaMoDz commented on Plugins/FreezeScene/Plugin.cs
> +}*/
I agree. Removed on next commit.

2022-08-31 21:29 UTC, AlFaMoDz commented on Plugins/FreezeScene/Plugin.cs
> +		{
I agree

2022-08-31 21:29 UTC, AlFaMoDz commented on Plugins/FreezeScene/Plugin.cs
> +			}
I agree

2022-08-31 21:29 UTC, AlFaMoDz commented on Plugins/FreezeScene/Plugin.cs
> +		return "";
I agree

2022-08-31 21:30 UTC, AlFaMoDz commented on Plugins/FreezeScene/README.md
> +The command must be sent by PM to the traffic:
I tested it and it works on both. Modified in the next commit

2022-08-31 21:31 UTC, AlFaMoDz commented
> 

Good idea! Adding regex support in the commit.

Btw, I'll rename the plugin to PauseMyScreen. I think it is a better name for this context.

2022-09-02 11:41 UTC, AlFaMoDz commented
All changes ready @wessupermare! I hope you dont kill me for my little C# knowledge 😂

2022-09-06 21:15 UTC, wessupermare requested changes
Just a _couple_ more style changes. Looking really good so far though!

2022-09-06 21:15 UTC, wessupermare commented on Plugins/PauseMyScreen/Plugin.cs
> +			@"RESUME$"
Should these be anchored to the beginning of the string as well? This will match `DON'T PAUSE` as `PAUSE$`, for instance.

2022-09-06 21:15 UTC, wessupermare commented on Plugins/PauseMyScreen/Plugin.cs
> +		_resume= new(regexes[1], RegexOptions.IgnoreCase);
```suggestion
		_pause = new(regexes[0], RegexOptions.IgnoreCase | RegexOptions.SingleLine | RegexOptions.Compiled);
		_resume= new(regexes[1], RegexOptions.IgnoreCase | RegexOptions.SingleLine | RegexOptions.Compiled);
```

Consider `RegexOptions.SingleLine` in case someone puts some strange characters in a message.

2022-09-06 21:15 UTC, wessupermare commented on Plugins/PauseMyScreen/Plugin.cs
> +    }
```suggestion
	private bool CheckMessage(string message, out string? command) 
	{
		if (_pause.IsMatch(message))
		{
			command = "pause";
			return true;
		}
		else if (_resume.IsMatch(message))
		{
			command = "resume";
			return true;
		}
		else
		{
			command = null;
			return false;
		}
	}
```
Formatting.

2022-09-06 21:24 UTC, AlFaMoDz commented on Plugins/PauseMyScreen/Plugin.cs
> +			@"RESUME$"
iirc, I tried it but the plugin didnt recognize the command afterwards, I'll try it now and let you know

2022-10-17 22:19 UTC, closed without merging